version: "3.5"
services:
  www:
    container_name: tpi-www
    build: ./build/www
    ports:
      - "8000:80"
    volumes:
      - ../../:/var/www/html/
    links:
      - mysql
    networks:
      - default

  mysql:
    container_name: tpi-mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: tpi
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
    networks:
      - default

  pma:
    container_name: tpi-pma
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    ports:
      - "8001:80"
    environment:
      PMA_USER: root
      PMA_PASSWORD: root
      PMA_HOST: mysql
